### ISSUE TITLE
Horizontal scroll also triggers title transition

### ISSUE THREAD

**Issue by KamilSztandur** [woltapp/wolt_modal_sheet#10]
You probably have to listen to only `ScrollNotifications` with `axis` set to `Axis.vertical` somewhere in your code.

**Showcase:**

![rerere](https://github.com/woltapp/wolt_modal_sheet/assets/61657553/c9b62523-c406-46bb-a114-ee494ad1b584)

**Comment by ulusoyca** [comment]
This is amazing to notice! Feel free to create PR. I will try to prioritize this.

**Comment by ulusoyca** [comment]
Fixed in https://github.com/woltapp/wolt_modal_sheet/pull/13

**Comment by ulusoyca** [comment]
Merged
