### ISSUE TITLE
This repo is not linked to pub.dev

### ISSUE THREAD

**Issue by KamilSztandur** [woltapp/wolt_modal_sheet#12]
You should link it there so more people can access it and give you valuable feedback.

https://pub.dev/packages/wolt_modal_sheet

![image](https://github.com/woltapp/wolt_modal_sheet/assets/61657553/40723b99-8941-47fd-9753-f091f4e3e0eb)

**Comment by ulusoyca** [comment]
Thanks. Fixed in https://github.com/woltapp/wolt_modal_sheet/pull/5. Next week will be released.
