### ISSUE TITLE
Test Failiing due to MissingPluginException flutter_keyboard_visibility on macOS

### ISSUE THREAD

**Issue by dhirajhimani** [woltapp/wolt_modal_sheet#123]
## Bug report

**Describe the bug**
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel
flutter_keyboard_visibility:
MissingPluginException(No implementation found for method listen on channel
flutter_keyboard_visibility)

### Steps to reproduce

With the latest version update 0.3.0 we are getting this exception on running UI tests.

### Expected behavior

Test should pass without error

---

## Additional context

Test which is failing context:-
1. open model_sheet on TAP of button
2. Golden Test compare the view with the saved screenshot 

---

**Comment by ulusoyca** [comment]
Thanks for reporting. I will check this but meanwhile can you check this one: https://github.com/MisterJimson/flutter_keyboard_visibility/issues/115

**Comment by ulusoyca** [comment]
@dhirajhimani Do you think we can share your learning in the ReadMe file? Do you think you can provide us how you fixed it so that we can share in ReadMe?

**Comment by dhirajhimani** [comment]
@ulusoyca I made the keyboard visibility to false, since this was the cause for failure
`KeyboardVisibilityTesting.setVisibilityForTesting(false);`
