### ISSUE TITLE
Add control for sheet insert animation Duration and Curve

### ISSUE THREAD

**Issue by kkoskenvirta** [woltapp/wolt_modal_sheet#131]
Sheet insert Animation Duration and Curve

It would be a great addition to give control for the sheet insert Duration and Curve.

**Comment by ulusoyca** [comment]
@TahaTesser Would it make sense to include this as part of ThemeData? What is the Flutter way of adding this in the cleanest way?

**Comment by TahaTesser** [comment]
Yes, we can add something like [AnimationStyle](https://main-api.flutter.dev/flutter/animation/AnimationStyle-class.html), this is actually part of multiple themes Including [ExpansionTileTheme](https://main-api.flutter.dev/flutter/material/ExpansionTileThemeData/expansionAnimationStyle.html) and widgets like [MaterialApp](https://main-api.flutter.dev/flutter/material/MaterialApp/themeAnimationStyle.html).

**Comment by ulusoyca** [comment]
@kkoskenvirta It is now possible to customize all animations for duration and curve. Refer to Readme: https://pub.dev/packages/wolt_modal_sheet#customizable-animations

**Comment by kkoskenvirta** [comment]
Amazing stuff! So glad to hear that this was added ⭐️
