### ISSUE TITLE
TextFields can not focus

### ISSUE THREAD

**Issue by kamami** [woltapp/wolt_modal_sheet#135]
## Bug report

**Describe the bug**
When clicking a TextField widget inside a WoltModalSheetPage the keyboard is not showing up.
I also tried the official example: https://github.com/woltapp/wolt_modal_sheet/blob/main/playground_navigator2/lib/modal/pages/sheet_page_with_text_field.dart#L53 
Just remove the autofocus and try to focus the TextField. You will see the keyboard tries to appear but gets somehow suppressed.

### Expected behavior
Keyboard should show up.

### Additional context
wolt_modal_sheet 0.4.0
latest Flutter release

**Comment by ulusoyca** [comment]
We will fix this today with a hotfix release.

**Comment by ulusoyca** [comment]
Should be fixed with 0.4.1
