### ISSUE TITLE
I found the background can not set as pure COlors.white?

### ISSUE THREAD

**Issue by luohao123** [woltapp/wolt_modal_sheet#139]
It will override by another tint color,

cosnider support it and fix it?

**Comment by ulusoyca** [comment]
At Wolt we are using pure white. Can you share a screenshot? Alternatively, to be on the safe side, you can set the tint color to be transparent in the theme data extension as in [this example](https://github.com/woltapp/wolt_modal_sheet/blob/main/example/lib/main.dart#L155) 

![image](https://github.com/woltapp/wolt_modal_sheet/assets/13782003/72ce47c2-36ca-4601-9665-496f82703163)

**Comment by luohao123** [comment]
@ulusoyca Am using themeData with useMaterial=3, and with a theme seed of Colors.purple.

So when I set COlors.red as background color, it works, but when set pure white, it will always overwrite.

**Comment by ulusoyca** [comment]
@luohao123 Have you tried to set the surfaceTintColor to `Colors.transparent`

**Comment by yusufnadar** [comment]
@luohao123 I was getting the same error, but after defining what @ulusoyca suggested it worked. This is my code:

AppTheme.defaultTheme: ThemeData(
    fontFamily: FontFamily.euclidCircularBRegular,
    scaffoldBackgroundColor: AppColors.scaffoldBgColor,
  ).copyWith(
    extensions: const <ThemeExtension>[
      WoltModalSheetThemeData(
        modalBarrierColor: Colors.transparent,
        backgroundColor: Colors.white,
        surfaceTintColor: Colors.transparent,
        mainContentScrollPhysics: ClampingScrollPhysics(),
      ),
    ],
  ),

**Comment by ulusoyca** [comment]
There is a fix by @yusufnadar . You can set the `surfaceTintColor` to Colors.transparent to avoid this. It will be released next week.

**Comment by luohao123** [comment]
BTW, wanna further ask, does it support some bouncing pop up animation built-in in walt? I really want the animation more smooth.
