### ISSUE TITLE
Update scroll physics for "no scroll glow"

### ISSUE THREAD

**Issue by aditya-wappnet** [woltapp/wolt_modal_sheet#147]
## What feature would you like to see?

I want Scroll Configruation use NOScrollGlow

**Comment by ulusoyca** [comment]
You can already set this through the theming: https://github.com/woltapp/wolt_modal_sheet/blob/main/lib/src/theme/wolt_modal_sheet_theme_data.dart#L133

Here is an example how to set the theming: https://github.com/woltapp/wolt_modal_sheet/blob/main/example/lib/main.dart#L161

**Comment by aditya-wappnet** [comment]
Still it's not working for me any help really it would be appreciated.

**Comment by ulusoyca** [comment]
This is addressed in this PR and will be released in 0.9.0
https://github.com/woltapp/wolt_modal_sheet/pull/283
