### ISSUE TITLE
When the TextField in the modal gets focus, the modal will shift up with the keyboard.

### ISSUE THREAD

**Issue by disonwei** [woltapp/wolt_modal_sheet#154]
When there is a TextField in wolt_modal_sheet and this TextField gets focus, the keyboard pops up and the entire wolt_modal_sheet will shift up. 

When the keyboard is retracted, wolt_modal_sheet will return to its original position. 

This causes the entire wolt_modal_sheet page to be reconstructed, which is not what I want. 

Is there a way to make the keyboard pop up directly overlay on wolt_modal_sheet without wolt_modal_sheet shifting up and down?

**Comment by AcarFurkan** [comment]
LGTM
