### ISSUE TITLE
[wolt app bug] ui text lost

### ISSUE THREAD

**Issue by l-7-l** [woltapp/wolt_modal_sheet#157]
## Bug report

**Describe the bug**

![微信图片_20240304123734](https://github.com/woltapp/wolt_modal_sheet/assets/20581031/1b67222f-22d5-4890-b194-1b6c7809bd48)

### Steps to reproduce

when as gesture use the wolt app, in the profile page, tap the continue with another service the all button's text is "button"

### unrelated question
What's page transition used in restaurants and stores page when tap the list card  to detail page?
---

**Comment by ulusoyca** [comment]
Hi!

I am closing this issue because this is not relevant to WoltModalSheet package, and the bug description is not clear. 

>What's page transition used in restaurants and stores page when tap the list card to detail page?

The WoltApp that customers make order is native app, not Flutter app. In the native app, custom transitions are used.
