### ISSUE TITLE
Back press on android dismiss "undismissible" bottomsheet. 

### ISSUE THREAD

**Issue by Bolling88** [woltapp/wolt_modal_sheet#160]
## Bug report

**Describe the bug**
If the bottom sheet is marked as dismissible false, then the bottom sheet can still be dismissed with the android back button. 

### Steps to reproduce

Open the bottom sheet that is not dismissible, and press the back button. 

### Expected behavior

It should not be dismissed.

**Comment by ulusoyca** [comment]
Dismissible false means that the modal sheet cannot be dismissed by taps in barrier or by dragging. Android Back Button is controlled by OS, and this should be done by wrapping the BackButtonListener Widget if Navigator 2.0 is in use, or PopScope if imperative navigation is in use. 

One example:
![image](https://github.com/woltapp/wolt_modal_sheet/assets/13782003/97561bc9-3e36-4cff-a87f-d99cae716d40)
