### ISSUE TITLE
TopBar background color (corner bug)

### ISSUE THREAD

**Issue by vicenterusso** [woltapp/wolt_modal_sheet#162]
## Bug report

There is a very thin border that Is bothering me on top bar

### Scenario 1 (with corner bug)

Code
```dart
WoltModalSheetPage(
  hasSabGradient: false,
  forceMaxHeight: true,
  topBar: Container(
    color: infoBlue,
    child: // etc ...

```

Image: (check corners)
![IMG_7367](https://github.com/woltapp/wolt_modal_sheet/assets/80538/55b246e9-2bf3-4e7c-ae0c-6f91ed6fe12b)
<img width="303" alt="Screenshot 2024-03-12 at 16 55 40" src="https://github.com/woltapp/wolt_modal_sheet/assets/80538/e74f467c-87cc-4fce-9f12-450bb77842d1">

### Scenario 2 (no corner bug)

Code 
```dart
WoltModalSheetPage(
  hasSabGradient: false,
  forceMaxHeight: true,
  backgroundColor: infoBlue,
  topBar: Container(
    child: // etc ...

```

Image:
![IMG_7368](https://github.com/woltapp/wolt_modal_sheet/assets/80538/5d572a3f-1681-4028-bb68-9328ef20def1)
<img width="303" alt="Screenshot 2024-03-12 at 16 58 27" src="https://github.com/woltapp/wolt_modal_sheet/assets/80538/b750918d-6015-4d34-b84b-fb4aee929371">

### Expected behavior

I cannot use second code because the whole modal with have "infoBlue" color. I expect a smooth corner without any white glitches.

**Comment by ulusoyca** [comment]
Do you see difference if you set the clip behavior in the theme data to `Clip.antiAliasWithSaveLayer` in https://github.com/woltapp/wolt_modal_sheet/blob/main/lib/src/theme/wolt_modal_sheet_theme_data.dart#L32

| antiAlias Vs antiAliasWithSaveLayer |
|--------|
| <img src="https://github.com/woltapp/wolt_modal_sheet/assets/13782003/9f12c073-63a1-44ac-b9a6-439147acef59"> |
| <img src="https://github.com/woltapp/wolt_modal_sheet/assets/13782003/62153fdd-9183-4cf3-bc45-9c8e7aaef784"> |

**Comment by ulusoyca** [comment]
This is a valid question. The[ Flutter SDK ](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/bottom_sheet.dart#L912)defaults to Clip.none. I can't recall the reasoning but I think we can default to Clip.antiAliasWithSaveLayer. What do you think @TahaTesser?

**Comment by vicenterusso** [comment]
> @vicenterusso Here is the PR: #164

Perfect!

**Comment by TahaTesser** [comment]
> This is a valid question. The[ Flutter SDK ](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/bottom_sheet.dart#L912)defaults to Clip.none. I can't recall the reasoning but I think we can default to Clip.antiAliasWithSaveLayer. What do you think @TahaTesser?

It defaults to none as clipping is not necessary when you don't provide a shape, but in the package, if you're always providing a shape then you can definitely the change the default
