### ISSUE TITLE
Add change width of dialog or BTS

### ISSUE THREAD

**Issue by Trung15010802** [woltapp/wolt_modal_sheet#170]
## What feature would you like to see?

I want show more content with dialog on web but i can't find a way to change width of Dialog
maxDialogWidth and minDialogWidth seem not working.
Only work if maxDialogWidth = minDialogWidth

**Comment by ulusoyca** [comment]
This is planned to be released with 0.7.0 with custom modal type positioning/layout.

**Comment by ulusoyca** [comment]
Fixed in https://github.com/woltapp/wolt_modal_sheet/pull/241
