### ISSUE TITLE
Floating bottom sheet

### ISSUE THREAD

**Issue by ulullul** [woltapp/wolt_modal_sheet#185]
Hello, thank you for a beautiful package.

I have a question. Is there a way to achieve a floating bottom sheet UI without losing the normal scroll flow from this library?

(this is the bottom sheet, and I want it to be floating like a popup)
![image](https://github.com/woltapp/wolt_modal_sheet/assets/46851597/58b4cb49-9d43-4ef0-9cb9-803d2f9f9949)

I've made my own implementation(I've just added padding around the content), but scrolling looks like this:

https://github.com/woltapp/wolt_modal_sheet/assets/46851597/bf73cb35-cd9d-4023-9203-8b0763d849ac

**Comment by ulusoyca** [comment]
This is planned to be released in the next release on 4th July.

**Comment by ulusoyca** [comment]
Added in https://github.com/woltapp/wolt_modal_sheet/pull/241
