### ISSUE TITLE
Position Modal (topCenter, bottomCenter)?

### ISSUE THREAD

**Issue by aPinix** [woltapp/wolt_modal_sheet#193]
## Please Help!

**Expected behavior**
I'm using the Modal and I want to position it on the topCenter or bottomCenter and it always does center of screen.

Is it possible? (see image)

Or having the background non-clickable so I can still make it the screen height and be able to click on the backdrop to dismiss.

Thanks in advance

![CleanShot 2024-05-03 at 10 44 00](https://github.com/woltapp/wolt_modal_sheet/assets/698523/bbf4f651-876d-4270-8003-ad06b7cdd3a1)

**Comment by ulusoyca** [comment]
It is not possible now, but it will be possible. It is on the roadmap.

**Comment by aPinix** [comment]
Thanks for the update! Cheers

**Comment by ulusoyca** [comment]
@aPinix I have started to working on customizing the modal layout and positioning. The next release will be all about modal type customization, including bottomsheet, dialog and side sheets.

**Comment by ulusoyca** [comment]
@aPinix 

This is a sneak peek for the next update. 

Introducing a new custom modal will be like this:

```dart
class TopNotificationModalSheet extends WoltModalType {
  const TopNotificationModalSheet()
      : super(
          shapeBorder: const RoundedRectangleBorder(
            borderRadius: BorderRadius.all(Radius.circular(24)),
          ),
          isDragEnabled: false,
          shouldForceContentToMaxHeight: false,
        );

  @override
  String routeLabel(BuildContext context) {
    final MaterialLocalizations localizations = MaterialLocalizations.of(context);
    return localizations.dialogLabel;
  }

  @override
  BoxConstraints modalContentBoxConstraints(Size availableSize) {
    return BoxConstraints(
      minWidth: availableSize.width - 64,
      maxWidth: availableSize.width - 64,
      minHeight: 0,
      maxHeight: availableSize.height * 0.6,
    );
  }

  @override
  Offset modalContentOffset(Size availableSize, Size modalContentSize) {
    return const Offset(32, 48);
  }

  @override
  Widget buildTransitions(
      BuildContext context,
      Animation<double> animation,
      Animation<double> secondaryAnimation,
      Widget child,
      ) {
    // Combined slide and fade transition.
    return FadeTransition(
      opacity: animation,
      child: SlideTransition(
        position: animation.drive(
          Tween(
            begin: const Offset(0.0, -0.1),  // Modified to start slightly above the screen
            end: Offset.zero,
          ).chain(CurveTween(curve: Curves.easeOutQuad)),  // Smoother curve for easing out
        ),
        child: child,
      ),
    );
  }
}
```

<video src="https://github.com/woltapp/wolt_modal_sheet/assets/13782003/03ab0204-baa4-451e-b9c8-5e576a985c93">

The next update will introduce custom modals.

**Comment by ulusoyca** [comment]
Fixed in https://github.com/woltapp/wolt_modal_sheet/pull/235
