### ISSUE TITLE
Prevent duplicate bottom sheet entry

### ISSUE THREAD

**Issue by ribuemsyne** [woltapp/wolt_modal_sheet#199]
Hi,
I liked to prevent wolt_modal_sheet not to open if there is another wolt modal sheet opened or the screen which requested the bottom sheet just destroyed/exited from navigation. Is there currently any feature for this?

**Comment by ulusoyca** [comment]
@ribuemsyne this should be done in state management level. I am working on a comprehensive demo app. You can do the following:
* Give a name to your modal sheet:
![image](https://github.com/woltapp/wolt_modal_sheet/assets/13782003/93e088dc-17c3-4a07-a1cf-c94fbc43e81b)
* Get the current route name: https://stackoverflow.com/a/54962118

Check if it is wolt:modal_route
