### ISSUE TITLE
The child provided to decorator functions is larger than it should be

### ISSUE THREAD

**Issue by benthillerkus** [woltapp/wolt_modal_sheet#201]
## Bug report

**Describe the bug**

With the `decorator` argument on `WoltModalSheet.show` you can provide a Widget tree in which the modal sheet will essentially be embedded as a child.
I want to use the decorator to add a blurred background to the sheet.
Unfortunately, the child provided to the decorator function is always as large as `maxPageHeight`, so when I wrap it with a `BackdropFilter` and a `ClipRRect`, I will essentially have a large blank blurred space on top of my sheet if the sheet resizes itself to be smaller than `maxPageHeight`.

<img width="756" alt="Screenshot 2024-05-09 at 21 52 49" src="https://github.com/woltapp/wolt_modal_sheet/assets/29630575/be9d02c9-a435-4cb1-9708-b925bdc6099e">

### Steps to reproduce

```dart
...
WoltModalSheet.show(
  ...
  decorator: (child) {
    return Align(
      alignment: Alignment.bottomCenter,
      child: ClipRRect(
        ...
        child: BackdropFilter(
          ...
          child: child,
        )
      )
    )
  }
  ...
)
```

### Expected behavior

I'd expect child to be only as large as the area that it paints with content.

**Comment by benthillerkus** [comment]
That or, move the decorator function to wrap a smaller part of the tree, ie a part that is being laid out by the *CustomMultiChildLayout

**Comment by ulusoyca** [comment]
Thanks for the contribution and the PR 💙  Closing this since your PR is merged.
