### ISSUE TITLE
add getter for `atRoot`

### ISSUE THREAD

**Issue by dickermoshe** [woltapp/wolt_modal_sheet#202]
## What feature would you like to see?

The current implementation of `WoltModalSheet`s navigator is really fantastic. 
It would be even better if there was a way to access how many pages are in the stack.

This is relevant for making a dynamic back button for a page.
If we knew that we were at index 0, it would show a close button that closes the sheet, or a back button that navigates back.

`_currentPageIndex` is private now, it would be awesome if it wasn't.

**Comment by ulusoyca** [comment]
@dickermoshe Thanks! Our conversation was really helpful. Would you consider opening a PR?

**Comment by dickermoshe** [comment]
https://github.com/woltapp/wolt_modal_sheet/pull/204

**Comment by dickermoshe** [comment]
My only complaint is that now `WoltModalSheet...` is polluted when looking for the `show` function.
![image](https://github.com/woltapp/wolt_modal_sheet/assets/75931499/b82ec8ca-4513-42d6-b1d9-ecf2352ddb14)

Like, these aren't really that helpful, the code is basically the same.
<img width="344" alt="image" src="https://github.com/woltapp/wolt_modal_sheet/assets/75931499/ae0b34b7-8036-4e51-b3c0-6028fc6ee66e">


Flutter uses .`of` for looking up controllers in context, that's what users are used to
I would've kept it all hidden behind `.of()`
![image](https://github.com/woltapp/wolt_modal_sheet/assets/75931499/7a3e9679-56d0-4010-aa6b-2c03622f6ae6)

This is just my humble opinion, otherwise the implementation is top notch

**Comment by ulusoyca** [comment]
Thank you for the feedback! Yes, makes sense. [This PR ](https://github.com/woltapp/wolt_modal_sheet/pull/208)removes the duplicate methods and sticks with `WoltModalSheet.of(context).method` type calls.
