### ISSUE TITLE
Dynamic Page Properties don't work

### ISSUE THREAD

**Issue by AcarFurkan** [woltapp/wolt_modal_sheet#205]
### Steps to reproduce

1.  Run Playground Example or open web example https://playgroundwoltexample.web.app
2. open bottom sheet
3. click `page with dynamic properties`
4. disable switch 
5. try drag

it shouldn't drag after switcher dissabled

## Additional context

![Simulator Screen Recording - iPhone 15 Pro - 2024-05-12 at 16 12 20](https://github.com/woltapp/wolt_modal_sheet/assets/65075121/e465001d-620b-4849-b714-0409d3afb28f)

---

**Comment by ulusoyca** [comment]
Fixed in https://github.com/woltapp/wolt_modal_sheet/pull/207
