### ISSUE TITLE
make topBarTitle visible all the time

### ISSUE THREAD

**Issue by LiLatee** [woltapp/wolt_modal_sheet#21]
Hi! Great work with the package! 😄 
As I understood `topBarTitle` is only visible when the bottom sheet is scrolled down. Is there a possibility to display `topBarTitle` all the time and do not use `pageTile`? 🤔 

Here is the example when `pageTitle` should not be used and `topBarTitle` should be visible all the time.
<img width="419" alt="image" src="https://github.com/woltapp/wolt_modal_sheet/assets/30510627/37ad9193-ee47-44eb-9369-95e83fe3d4c2">

**Comment by ulusoyca** [comment]
This is doable. We will come up with a roadmap for the package development. ping @yunusemrebakir

**Comment by arbile26** [comment]
I really need something like this.

**Comment by ulusoyca** [comment]
@arbile26  @LiLatee The PR is open. This feature is planning to be landed in next release. Please comment if it answers your use case.
https://github.com/woltapp/wolt_modal_sheet/pull/31

**Comment by ulusoyca** [comment]
Merged.
