### ISSUE TITLE
Structured Readme for easy onboarding

### ISSUE THREAD

**Issue by ulusoyca** [woltapp/wolt_modal_sheet#232]
## Problem Statement
The extensive and detailed documentation provided in the Readme section of the WoltModalSheet package, while comprehensive, can be overwhelming for new users. This complexity may hinder easy onboarding and efficient usage of the package, especially for beginners who are looking to get up to speed rapidly.

## Proposed Solution
Introduce a structured documentation system within the Readme that categorizes information based on the proficiency level of package user: Starter, Intermediate, and Advanced. This approach will help users navigate the documentation more effectively, allowing them to access information that matches their current understanding and needs.

### Have top level three categories

- Starter Level: Focus on basic setup, simple usage examples, and core functionalities. This section should guide new users through initial installation, basic configurations, and simple demonstrations of the package’s capabilities.

- Intermediate Level: Dive into more detailed features and customization options that the package offers. Include sections on moderate complexity tasks, such as custom animations, state management integrations, and using intermediate-level components of the modal sheet.

- Advanced Level: Provide in-depth technical details for advanced users, such as deep customizations, performance optimizations, and complex use case implementations. This might also cover contributions guidelines, detailed architectural discussions, and advanced state management techniques.

**Comment by ulusoyca** [comment]
Replace `motion animation` with `motion` only.

**Comment by moshOntong-IT** [comment]
> Replace `motion animation` with `motion` only.

I think the documentation of popping page should be update as well

> #### Popping Page
> Using pop method, you can remove the last page of the navigation stack. If the
> user is on the last page, the method will navigate to the previous page.
>     
> ```dart
> bool popped = WoltModalSheet.of(context).pop();
> ```

I think it should be `popPage()`
