### ISSUE TITLE
 WoltModalSheet.show does not not reflect the state in real time kindly assist, how can one use statefulbuilder

### ISSUE THREAD

**Issue by leadpresence** [woltapp/wolt_modal_sheet#236]

**Comment by ulusoyca** [comment]
Can you please add more description?

**Comment by Hidayat1999** [comment]
Hi @leadpresence, I was trying to setState as well but it seems to be not be updating the state inside the modal. Using ValueListenableBuilder instead works

**Comment by ulusoyca** [comment]
Hi, 

The v0.8.0 has improved the Readme and added [this section](https://pub.dev/packages/wolt_modal_sheet#modal-level-decoration) to explain the state management at modal level.
