### ISSUE TITLE
Add side sheet modal type

### ISSUE THREAD

**Issue by ulusoyca** [woltapp/wolt_modal_sheet#25]
Currently we are returning bottom sheet or dialog:

```dart
enum WoltModalType {
  bottomSheet,
  dialog;
}
````
It is possible to add side sheet option: https://m3.material.io/components/side-sheets/overview

**Comment by MahanRahmati** [comment]
@ulusoyca Hello there. Is this planned?

**Comment by ulusoyca** [comment]
> @ulusoyca Hello there. Is this planned?

Yes, next release 4th July will support side sheet. [Here](https://github.com/woltapp/wolt_modal_sheet/tree/customize-modal-type) is the WIP branch. Currently waiting the design specs for the side sheet from the designer team.

**Comment by ulusoyca** [comment]
Fixed in https://github.com/woltapp/wolt_modal_sheet/pull/241
