### ISSUE TITLE
Close bottom sheet on scroll

### ISSUE THREAD

**Issue by josebejao** [woltapp/wolt_modal_sheet#262]
Hi,

It's any possibility to close bottom sheet when you are on top of scroll and swipe down ? Like if we touch in title with drag enabled, but on the scroll widget. 

Thank you

**Comment by ulusoyca** [comment]
@MbIXjkee This is a good use case. Do you think that this would work in the new scroll view?

**Comment by ulusoyca** [comment]
We are working on this.

**Comment by AcarFurkan** [comment]
Hey @ulusoyca @josebejao ,
I made a demo, is this what we want?
https://github.com/user-attachments/assets/954a541f-21d9-48bf-8f82-9bb0045d15f4

**Comment by ulusoyca** [comment]
> Hey @ulusoyca @josebejao ,
> 
> I made a demo, is this what we want?
> 
> https://github.com/user-attachments/assets/954a541f-21d9-48bf-8f82-9bb0045d15f4
> 
> 
> 
> 

Yes 🤩 if only this is the behaviour when scroll position is 0. What happens in scrolled case?

**Comment by AcarFurkan** [comment]
> > Hey @ulusoyca @josebejao ,
> > I made a demo, is this what we want?
> > >>1.00<<
> >   
> >     
> >     
> > 
> >     wolt.mp4
> 
> Yes 🤩 if only this is the behaviour when scroll position is 0. What happens in scrolled case?

This is up to us. If we want, we can use drag properties like the one used by `WoltModalSheetContentGestureDetector` right now. Or we can define another behavior :)

**Comment by ulusoyca** [comment]
The default behavior should be enable drag to dismiss gesture on list view area when main content scroll position is 0.

**Comment by AcarFurkan** [comment]
On it> The default behavior should be enable drag to dismiss gesture on list view area when main content scroll position is 0.

**Comment by AcarFurkan** [comment]
> The default behavior should be enable drag to dismiss gesture on list view area when main content scroll position is 0.
On it

**Comment by AcarFurkan** [comment]
On it
> The default behavior should be enable drag to dismiss gesture on list view area when main content scroll position is 0.

**Comment by ulusoyca** [comment]
> On it
> > The default behavior should be enable drag to dismiss gesture on list view area when main content scroll position is 0.
> 
This is the default behaviour:

https://github.com/user-attachments/assets/b58beb83-be5d-4e19-aced-3ad0f2bbd6f1

**Comment by josebejao** [comment]
That's it, thank you so much.

**Comment by ulusoyca** [comment]
> That's it, thank you so much.

@durannumit and @AcarFurkan are working on this feature. I am also looking forward to see how they will address this 👀

**Comment by AcarFurkan** [comment]
> > On it
> > > The default behavior should be enable drag to dismiss gesture on list view area when main content scroll position is 0.
> 
> This is the default behaviour:
> 
>  trim.5AD7E686-B874-4606-85A7-FB7E04D53612.MOV


https://github.com/user-attachments/assets/f1418cf8-dacf-424c-81ff-e353a87b2b93

**Comment by AcarFurkan** [comment]
Thank youu :) I wrote some bad code to make a quick demo. If I don't have any extra work today or tomorrow, I want to clean it up and open a PR :) coming soon

**Comment by ulusoyca** [comment]
I am gonna be honest. I spent around 30 mins to fix this, and couldn't do it. Really looking forward to it. 🙇

**Comment by ulusoyca** [comment]
@AcarFurkan I improved your solution. It does not have to be a bottom sheet. Our generic solution also does the same for custom modal types and handles all the edge positions considering selected dismiss direction.


https://github.com/user-attachments/assets/a227d8ba-874a-487f-b9ae-df9558998b1a

**Comment by ulusoyca** [comment]
@josebejao This is released with 0.9.0
