### ISSUE TITLE
When sheet is scrollable drag to close is not working

### ISSUE THREAD

**Issue by dario-digregorio** [woltapp/wolt_modal_sheet#282]
## Bug report

**Describe the bug**
I noticed when having a scrollable sheet the drag to close gesture is not working properly. Only when grabbing by the handle you can close the modal. If there is no scrollable content the modal can be closed by dragging the content, like expected.

### Steps to reproduce

1. Go to the wolt modal playground
2. Select bottom Sheet
3. See drag behavior when dragging a scrollable content vs a non scrollable content

### Expected behavior

Should be able to drag and close no matter if it is a scrollable or not

---

## Additional context

https://github.com/user-attachments/assets/60abbd69-6cdd-4239-8f23-e36c75fa1b93

---

**Comment by ulusoyca** [comment]
Thanks @dario-digregorio

Closing this since it is duplicate: https://github.com/woltapp/wolt_modal_sheet/issues/262

Ping @AcarFurkan @durannumit

**Comment by ulusoyca** [comment]
@dario-digregorio do you think you have time to check this issue as well? If yes, don't hesitate for contribution :)

**Comment by ulusoyca** [comment]
@dario-digregorio 0.9.0 added this feature.
