### ISSUE TITLE
Leading Nav Widget is distorted

### ISSUE THREAD

**Issue by agordeev** [woltapp/wolt_modal_sheet#287]
Reproducible on the example project without any modification.

`IconButton` should be round, but it's stretched vertically.

<img width="348" alt="Screenshot 2024-08-04 at 11 33 02" src="https://github.com/user-attachments/assets/c2122db5-9781-4de5-add3-e0fadf3c482b">

**Comment by ulusoyca** [comment]
Leading nav bar widget is fully customizeable. You should be able to adjust it according to your specs. For example, with very simple modification, it looks different.

| Before | After |
|--------|--------|
| <img width="627" alt="image" src="https://github.com/user-attachments/assets/4ce3d000-3875-498f-9371-5c13d1700f46"> | <img width="613" alt="image" src="https://github.com/user-attachments/assets/7b3dd6c0-fc8c-4339-9668-fb70978c1ab3"> |
