### ISSUE TITLE
Make _pages getter public

### ISSUE THREAD

**Issue by Albertbol** [woltapp/wolt_modal_sheet#297]
## What feature would you like to see?
I would like to have access to pages.
Please tell us the problem you are running into that led to you wanting a new feature.
I cant see total of pages in the stack to see that its a last page.

**Comment by ulusoyca** [comment]
This is a great suggestion and added in https://github.com/woltapp/wolt_modal_sheet/pull/299

Exposing the page list, and also exposing helper getters to detect if the current page is first/last really improved the example playground app. You can see yourself in this PR diff: https://github.com/woltapp/wolt_modal_sheet/pull/299

**Comment by ulusoyca** [comment]
Released https://pub.dev/packages/wolt_modal_sheet/changelog @Albertbol
