### ISSUE TITLE
How to remove top bar?

### ISSUE THREAD

**Issue by hammamziadeh10** [woltapp/wolt_modal_sheet#30]
Hey guys!

I want to customize the page and so therefore I want to remove the top bar fully. Is that possible, if so how? If not, is it something you could implement?

Kind regards

**Comment by ulusoyca** [comment]
Ok, I guess we need to make it more visible but the `WoltModalSheetPage` has a field 
```dart
  /// Indicates whether the top bar should be visible or hidden when the page is scrolled.
  final bool isTopBarVisibleWhenScrolled;
```
When set to false, it gives the following result:

https://github.com/woltapp/wolt_modal_sheet/assets/13782003/ab3e6ea3-2828-4c9b-9378-d0206c7d9952

Is this what you are looking for?

**Comment by hammamziadeh10** [comment]
Thanks for the response,

Unfortunately, no. I meant removing top bar completely so I can customize the whole sheet the way I want; not just when scrolled. For example, I will have one of my bottom sheets be at max height and it won't be draggable; so I don't want that small drag widget apparent at all.

**Comment by ulusoyca** [comment]
> Thanks for the response,
> 
> Unfortunately, no. I meant removing top bar completely so I can customize the whole sheet the way I want; not just when scrolled. For example, I will have one of my bottom sheets be at max height and it won't be draggable; so I don't want that small drag widget apparent at all.

Have you tried `forceMaxHeight` property? 
https://github.com/woltapp/wolt_modal_sheet/blob/main/lib/src/modal_page/wolt_modal_sheet_page.dart#L48

**Comment by hammamziadeh10** [comment]
Yep, the max height is not an issue; it works just fine. The problem is that I can't remove the whole tab bar so I can customize the page the way I want.

**Comment by ulusoyca** [comment]
> Yep, the max height is not an issue; it works just fine. The problem is that I can't remove the whole tab bar so I can customize the page the way I want.

Can you provide a visual explanation of what you don't want?

**Comment by ulusoyca** [comment]
Do you think [this PR ](https://github.com/woltapp/wolt_modal_sheet/pull/31)adds features according to your wish?

**Comment by hammamziadeh10** [comment]
![IMG_58B829ECB036-1](https://github.com/woltapp/wolt_modal_sheet/assets/98935501/0e489507-b0df-47dd-aa8b-0c61c12515a2)

Almost. But you see that line at the top of the bottom sheet? I want to remove that too. I also want to be able to start my content at the very top. Basically, just a clean sheet where I can place anything wherever I want. Please let me know if that makes more sense.

**Comment by ulusoyca** [comment]
@hammamziadeh10 Can you please check this PR and see if it answers your request?
https://github.com/woltapp/wolt_modal_sheet/pull/42

**Comment by hammamziadeh10** [comment]
Unfortunately it still doesn't solve it. Although it works in dialog, in bottom sheet, it's not doing it probably. That **small grey drag line** on the top of the bottom sheet is still visible even though **I set hasTopBarLayer: false**. Additionally,  even after setting padding to 0, the content **doesn't start from the top; there is still some space**. 

Steps to reproduce:
1. Download project
2. Open 'example'
3. Go to page 1
4. Set hasTopBarLayer: false
5. Set isTopBarLayerAlwaysVisible: false,
6. Set left,top,right padding to 0.
7. Remove trailing widget.
<img width="426" alt="Screenshot 2023-08-18 at 7 30 21 PM" src="https://github.com/woltapp/wolt_modal_sheet/assets/98935501/c70f5de9-f923-4af8-a1ea-641ae04f9da4">

**Comment by ulusoyca** [comment]
>That small grey drag line on the top of the bottom sheet is still visible even though I set hasTopBarLayer: false
This is the drag handle.  You can do two things:
1. Apply padding to your content so that the content is below the handle from top.
2. Wait for [this PR to be merged](https://github.com/woltapp/wolt_modal_sheet/pull/44/files#diff-1002200c08147325f7bf959434112783d64c6adcff796d1d7aac5b7349c5f467R34) so that you can hide the drag handle through the setting in ThemeData.

**Comment by hammamziadeh10** [comment]
I'll wait for the PR but **please also take care of the padding or margin that is on the top of the sheet as well!** Here is what I mean: 
<img width="426" alt="Screenshot 2023-08-19 at 4 33 33 PM" src="https://github.com/woltapp/wolt_modal_sheet/assets/98935501/82ee9936-d774-4b08-842b-2d94e7def6d0">
If I remove the top bar and drag handle, I **must** be able to start my content from the very top.

**Comment by ulusoyca** [comment]
I ran this PR and it looks like this is already handled [in this PR
](https://github.com/woltapp/wolt_modal_sheet/pull/45)
<img width="573" alt="image" src="https://github.com/woltapp/wolt_modal_sheet/assets/13782003/3396eac1-727b-42e3-bd91-9286a0281306">

**Comment by hammamziadeh10** [comment]
If that's the case, that would be great! Once the PR is merged, I'll try it and I'll let you know

**Comment by ulusoyca** [comment]
The PR is merged: https://github.com/woltapp/wolt_modal_sheet/pull/45
