### ISSUE TITLE
Sticky action bar covers input fields when keyboard is visible

### ISSUE THREAD

**Issue by Albertbol** [woltapp/wolt_modal_sheet#305]
## Bug report

When a sticky action bar is used in `WoltBottomSheetType` with a fixed height of 100px, and a `SizedBox` of 100px is added at the bottom, tapping on the input field causes the sticky action bar to fly up and cover the input field.

### Steps to reproduce

Described above

### Expected behavior

Sticky action bar should not maybe come up, or no cover input field.

---

## Additional context

---

**Comment by ulusoyca** [comment]
Hi, Can you provide a Screen recording? You should be able to add bottom padding larger than 100px to your main content which will make your main content visible, or scrollable.

**Comment by Albertbol** [comment]
Hey, with bottom padding you mean sized box in the bottom of `mainContentSliversBuilder`, correct? Than i tried it, did not help.

https://github.com/user-attachments/assets/df9e0e7c-d6e4-4b82-9e7b-73c127fb05da

**Comment by ulusoyca** [comment]
I mean this example: https://github.com/woltapp/wolt_modal_sheet/blob/main/coffee_maker/lib/home/online/modal_pages/add_water/water_settings_modal_page.dart#L35

You can test the [sample app](https://coffeemakerexample.web.app/) and check the water setting.

**Comment by Albertbol** [comment]
What would be equivalent for Sliver as i have:
mainContentSliversBuilder
which expects List of widgets.

**Comment by Albertbol** [comment]
I got the same result with example above, tried with `WoltModalSheetPage` like in the link you have sent.

**Comment by Albertbol** [comment]
Open the water settings on your phone you will get the same result:
https://coffeemakerexample.web.app/
It will cover water temperature field.
Tested on iPhone 13.

**Comment by ulusoyca** [comment]
Can you try this? https://github.com/woltapp/wolt_modal_sheet/pull/306/files#diff-72fd825ad17ce7800a2078e06f0dff1e12836ee59760465e78d9a5d222cebd15R139

**Comment by Albertbol** [comment]
Nope its not fixing input focus issue, still the same.

**Comment by ulusoyca** [comment]
Are you using `scrollPadding` in your text field?

**Comment by Albertbol** [comment]
Nope, I was not using it. Tested and this issue can be solved with it, but basically, I need to add `scrollPadding` equal to the bottom-sized box padding multiplied by 2 to see the input. 
Is that how it's supposed to be, and is that the solution?

**Comment by ulusoyca** [comment]
Unfortunately, I would only suggest you to use the value that can solve the height. We are working on solving this in a way that you wont need to consider the bottom padding because the entire page will be a widget.

**Comment by Albertbol** [comment]
Ok thank you @ulusoyca for so quick responses on the open source project and also for such a great project itself. 👏

**Comment by ulusoyca** [comment]
Happy to hear! Please consider giving a star on Github and like on pub.dev which helps us to get more resources to spend on this project 🥳
