### ISSUE TITLE
Some of the tests are failing in Flutter 3.16.0 and newer versions

### ISSUE THREAD

**Issue by jebstern** [woltapp/wolt_modal_sheet#320]
## Bug report

**Describe the bug**
Just wanted to inform you that some of the tests are failing in Flutter 3.16.0 and newer versions.

### Steps to reproduce

1. Use Flutter 3.16.0 or newer version.
2. Run tests.
3. Some of the tests fail.

### Expected behavior

Tests should all pass.

---

## Additional context

In Flutter 3.16.0, the `ThemeData.useMaterial3` flag is true by default, which seems to possible be the root cause.

By changing the `useMaterial3` boolean, tests would fail when true & succeed when false

![image](https://github.com/user-attachments/assets/29cf0238-c8df-4685-87c8-cb060962fa22)
_wolt_modal_sheet.dart_

---

**Comment by ulusoyca** [comment]
Thanks for the report! Do you mind fixing the tests with a PR?

**Comment by ulusoyca** [comment]
Oh actually, this PR by @mhadaily is fixing it: https://github.com/woltapp/wolt_modal_sheet/pull/315

I guess :)

**Comment by jebstern** [comment]
Sorry for late reply!
Okay, no need then 😄
