### ISSUE TITLE
GestureDetector onScale inside modal sheet child

### ISSUE THREAD

**Issue by nico3587** [woltapp/wolt_modal_sheet#322]
I'm using a bottom modal sheet to display a camera record and replay page. On this page, I have a Container that represents a timeline of available recordings. This allows me to select the specific recording I want to play. I use a GestureDetector with the onScaleUpdate callback to handle horizontal dragging and pinch zoom.

However, when the timeline selector is placed inside the modal sheet, I noticed that the onScaleUpdate callback doesn't receive events when pointerCount is 1.

To reproduce the issue, you can place a GestureDetector inside a modal sheet and print details.pointerCount inside the onScaleUpdate callback. You'll observe that it only prints when pointerCount is greater than 1.

I was able to fix this issue by modifying the package code in the file wolt_modal_sheet_drag_to_dismiss_detector.dart.

**I change it from :**

```dart
child: GestureDetector(
        excludeFromSemantics: true,
        onVerticalDragUpdate: (details) => isVerticalDismissAllowed ? _handleVerticalDragUpdate(details) : null,
        onVerticalDragEnd: (details) => isVerticalDismissAllowed ? _handleVerticalDragEnd(context, details) : null,
        onHorizontalDragUpdate: (details) =>
            isHorizontalDismissAllowed ? _handleHorizontalDragUpdate(context, details) : null,
        onHorizontalDragEnd: (details) =>
            isHorizontalDismissAllowed ? _handleHorizontalDragEnd(context, details) : null,
        child: child,
      ),
```

**To this :**

```dart
child: GestureDetector(
        excludeFromSemantics: true,
        onVerticalDragUpdate: isVerticalDismissAllowed ? (details) => _handleVerticalDragUpdate(details) : null,
        onVerticalDragEnd: isVerticalDismissAllowed ? (details) => _handleVerticalDragEnd(context, details) : null,
        onHorizontalDragUpdate:
            isHorizontalDismissAllowed ? (details) => _handleHorizontalDragUpdate(context, details) : null,
        onHorizontalDragEnd:
            isHorizontalDismissAllowed ? (details) => _handleHorizontalDragEnd(context, details) : null,
        child: child,
      ),
```

Before, even when isHorizontalDismissAllowed was false, the onHorizontalDragUpdate callback was set to "(details) => null", instead of directly to "null".

Do you think this issue could be fixed in the package?

**Comment by ulusoyca** [comment]
@nico3587 This is a very good catch. Would you like to be a contributor and create a PR? as soon as it is merged, I can create a hotfix.

**Comment by nico3587** [comment]
Yes, why not? I do like this package, and I would be pleased to contribute to it!

**Comment by ulusoyca** [comment]
@nico3587 Thanks for the contribution. I am closing this now, and today or tomorrow releasing a hotfix.

**Comment by ulusoyca** [comment]
@AcarFurkan promised to handle the release this weekend. Thanks for the patience!

**Comment by ulusoyca** [comment]
@nico3587 released https://pub.dev/packages/wolt_modal_sheet/changelog
