### ISSUE TITLE
[Refactor]: Folder structure improvement proposal

### ISSUE THREAD

**Issue by mukireus** [woltapp/wolt_modal_sheet#345]
## What feature would you like to see?

The current folder structure appears disorganized, with example projects and packages nested within each other. It is recommended to refactor the folder structure to provide better clarity and organization.

By restructuring the folder organization, users who only include this package in their projects will avoid downloading unused example files when executing `flutter pub get`. This change is expected to improve the performance of the command execution by reducing the amount of data that needs to be fetched.

## See

| Before | After |
|--------|--------|
| ![Screenshot Before](https://github.com/user-attachments/assets/7de6bb17-e690-4877-b991-48a96dc96e25) | ![Screenshot After](https://github.com/user-attachments/assets/b950189b-c22c-4d73-9c42-e01c40014360) |

**Comment by ulusoyca** [comment]
Thanks for the proposal. We need the example folder separately AFAIK to be able to show [this page](https://pub.dev/packages/wolt_modal_sheet/example) on pub dev. Otherwise examples folder looks good. I would also like to keep widgetbook inside coffee_maker_navigator_2 since it belongs to that specific project.

Other than than wolt_state_management and wolt_di also only used in coffee_maker_navigator_2. We should include them under it imo.

**Comment by mukireus** [comment]
[Package layout conventions - Examples](https://dart.dev/tools/pub/package-layout#examples)
According to the explanation on this page, we can generate markdown files to add and redirect example project paths. For instance, the [flutrlint](https://pub.dev/packages/flutrlint/example) project already includes a markdown file under the "Example" tab, which can serve this purpose.

We can re-add the Widgetbook project as you suggested.

I recommend moving the `wolt_di` and `wolt_state_management` packages to the packages folder for easier access in future projects. These packages are currently located in the root directory.

**Comment by mukireus** [comment]
Also you can check this PR: [[DRAFT] Refactor - Clean folder structure](https://github.com/mukireus/wolt_modal_sheet/pull/1)

**Comment by ulusoyca** [comment]
@mukireus The draft PR looks good. We can merge this way. @TahaTesser what is your take?

@mukireus we will also need to update the ReadMe.

**Comment by TahaTesser** [comment]
Looks good to me. This will make the samples navigation a lot better. I wanted to do this but couldn't get around it.

**Comment by mukireus** [comment]
@ulusoyca Should we also move the `wolt_modal_sheet` package into the packages directory? I can open a separate PR for this, or we can pair on it together. We can close the issue if needed.

**Comment by ulusoyca** [comment]
@mukireus Thanks for the great changes, and the PR! This repo is made for Wolt Modal Sheet, the other packages are planned to be released a packages during next year in separate repos, so let's keep them under the packages folder for now. I am closing this issue. Once more, thanks for the great work.
