### ISSUE TITLE
Rebuild of complete WoltModalSheetPage after state change

### ISSUE THREAD

**Issue by mschlegelaware** [woltapp/wolt_modal_sheet#348]
## What feature would you like to see?

This is a shorter an abstract version of my problem. But in general I want to show a button inside a `WoltModalSheetPage`, when the button is clicked I want to toggle a state change (prefered via bloc). This state change should rebuild the whole `WoltModalSheetPage` including changes of the `forceMaxHeight` property from true to false and vice versa, and should rebuild the UI accordingly.

So far I just managed to access the bloc state inside the topBar and child using `BlocBuilder` (or `.select`), and I can rebuild the UI inside the sheet page properly. But for the `forceMaxHeight` property I can just use `context.read` which is not listening to state changes. `.select` is giving me an error that I can not use select outside of build functions (which makes sense).

I tried to use the `pageContentDecorator` and `modalDecorator` to provide and listen to state changes of my bloc, which is working, but the child widget is not rebuild. I also tried to wrap the child inside a key, which I updated according to the state of my bloc. But the `WoltModalSheetPage` (`forceMaxHeight`) was never re-build.

Maybe I just miss something little and  my scenario is easily doable, but I can just not figure out how. Could you please hint me in the right direction?

**Comment by ulusoyca** [comment]
Hi @mschlegelaware have you checked the documentation? We have this example:
https://github.com/woltapp/wolt_modal_sheet/blob/main/examples/playground/lib/home/pages/sheet_page_with_update_page_method.dart#L40

https://pub.dev/documentation/wolt_modal_sheet/latest/wolt_modal_sheet/WoltModalSheetState/updateCurrentPage.html

I quickly tested this:

<video src="

https://github.com/user-attachments/assets/0640986a-9cdc-462f-8791-8c0bc4180778
">

**Comment by mschlegelaware** [comment]
@ulusoyca Ah thank, you so much for this 🥇! I searched in the docs and repo but that one I just missed. I guess that will solve all the problems!
