### ISSUE TITLE
onModalDismissedWithDrag does not stop the modal from closing

### ISSUE THREAD

**Issue by jkoenig134** [woltapp/wolt_modal_sheet#38]
As I see the `onModalDismissedWithDrag` it should make it possible to prevent the modal from closing in different situations.

Whats working is the following: `onModalDismissedWithBarrierTap` stops the modal from closing when tapping outside the modal when I assign a function that doesn't runs `Navigator.of(context).pop();`.

This also doesn't work on main (I got the dependency via git), where the `onModalDismissedWithDrag` is correctly assigned via https://github.com/woltapp/wolt_modal_sheet/pull/22.

**Comment by ulusoyca** [comment]
`onModalDismissedWithDrag` should only be used for integrating the modal for Navigator 2.0. If the modal sheet is imperatively pushed, and this field is not null, `Navigator.pop` should be called. Otherwise, it might have unexpected issues.

**Comment by jkoenig134** [comment]
@ulusoyca my goal is to programmatically control if the user can dismiss the sheet (or dialog) from inside the sheet.

This is possible with the `onModalDismissedWithBarrierTap` method, but not for the `onModalDismissedWithDrag` method.

I get that these methods are not for this purpose, but it would be really got to have this method updated (or have another one) to accomplish this.

**Comment by jkoenig134** [comment]
```dart
onModalDismissedWithBarrierTap: () {
  if (someCondition) {
    // do not pop
    
    return;
  }
  
  debugPrint('Closed modal sheet with barrier tap');
  Navigator.of(context).pop();
  pageIndexNotifier.value = 0;
},
onModalDismissedWithDrag: () {
  if (someCondition) {
    // do not pop
    
    return;
  }

  debugPrint('Closed modal sheet with drag');
  Navigator.of(context).pop();
  pageIndexNotifier.value = 0;
}
```

this is the code snippet I am using.

**Comment by jkoenig134** [comment]
I'd suggest to add new methods (e.g. `onBeforeModalDismissedWithBarrierTap` and `onBeforeModalDismissedWithDrag`) that return booleans to tell the modal if it is allowed to close or not.

**Comment by ulusoyca** [comment]
I got your point. So we have [`enableDrag`](https://github.com/woltapp/wolt_modal_sheet/blob/main/lib/src/wolt_modal_sheet.dart#L69) parameter set before showing the modal sheet, but is it so that you want to dynamically set enableDrag after the bottomsheet is shown?

**Comment by jkoenig134** [comment]
Exactly!

**Comment by ulusoyca** [comment]
@jkoenig134 [This PR](https://github.com/woltapp/wolt_modal_sheet/pull/45) should address your use case. Thanks for the feedback!

**Comment by jkoenig134** [comment]
Thank you! This is exactly what I needed. Will this also stop the dismiss by outside tap?

**Comment by ulusoyca** [comment]
@jkoenig134 Preventing dismiss by outside tap is already possible in the current version as you mentioned. This PR only prevents dismiss by drag.

**Comment by jkoenig134** [comment]
Sure, but I think I am misusing that function! But if not, I am fine.

**Comment by ulusoyca** [comment]
@jkoenig134 It probably needs a better naming and commenting. I am creating a ticket for it, but the way you use it was the purpose of this field together with integration for Navigator 2.0

**Comment by ulusoyca** [comment]
Merged in https://github.com/woltapp/wolt_modal_sheet/pull/45
