### ISSUE TITLE
Can I rebuild pages in pageListBuilder?

### ISSUE THREAD

**Issue by milansurelia** [woltapp/wolt_modal_sheet#40]
I am creating a pageBuilder with dynamic pages using List.generate I have passed the childList to every page based on index.

I am updating data[1].childList from 0th Page, but when I switch to next Page I doesn't reflect the updated data.

Can anyone have the solution to achieve this? 

Here is code snippet of my code:
```
WoltModalSheet.show<void>(
    pageIndexNotifier: pageIndexNotifier,
    context: context,

    pageListBuilder: (modalSheetContext) {
      return List.generate(data?.length, (index) {
        final item = data?[index];
        return WoltModalSheetPage(
          pageTitle: Text(item?.label ?? ''),
          singleChildContent: CustomListViewSheet(
            items: data?[index]?.subList,
            selectedItems: data?[index]?.selectedValue,
            context: context,
            index: index,
          ),
        );
      });
    },
    modalTypeBuilder: (context) => WoltModalType.bottomSheet,
    onModalDismissedWithBarrierTap: () {
      debugPrint('Closed modal sheet with barrier tap');
      pageIndexNotifier.value = 0;
    },
  );
```

**Comment by ulusoyca** [comment]
@milansurelia For the state management, you need to use the `decorator` field. You can refer to the [`coffeeMaker` example app](https://github.com/woltapp/wolt_modal_sheet/blob/7850005f78752ea17cd231ecb67fa7b1dfd52b2a/coffee_maker/lib/home/online/store_online_content.dart#L114). 

1. Create your ChangeNotfiier, Bloc or your favorite state management solution. 
2. Add the `ChangeNotifierProvider` or the `InheritedWidget` to the `decorator` field.
3. When you update the state in your ,`ChangeNotifierProvider` or the `InheritedWidget` it should rebuild the pages.

**Comment by milansurelia** [comment]
Thank You @ulusoyca for the response.`decorator` field helped me solve the issue 🎉

**Comment by becjit** [comment]
@milansurelia  you mind shaading the code snippet. I am trying like this but not able to get it work

approach 1

` WoltModalSheet.show<void>(
          context: context,
          decorator: (child) {
            return BlocProvider<BlinkBloc>.value(
                value: _blinkBloc,
                child: BlocBuilder<BlinkBloc, BlinkState>(
                  builder: (context, state) {
                    return child;
                  },
                ));
          },
          pageListBuilder: (modalSheetContext) {
            return [
              page1(modalSheetContext, isError: isError),
            ];
          },
`

second approach

 ```
 decorator: (child) {
            return BlocProvider<BlinkBloc>.value(
                value: _blinkBloc,
                child: 
                    return child;
                 
                );
          },
          pageListBuilder: (modalSheetContext) {
            return [
              page1(modalSheetContext, isError: isError),
            ];
          },

and then trying to wrap my widget inside the modal with blocbuilder. Both are not working. 
```

**Comment by becjit** [comment]
Never mind I got the second approach working! Is the first approach a valid one i.e. wrapping the child with the blocbuilder?

**Comment by kamami** [comment]
Can anyone please share a working example with bloc? I make use of two different cubits in the modal sheet, but they are not updating correctly.

**Comment by ulusoyca** [comment]
Hi @kamami ! Have you checked the existing examples with the `cubit`? Here is the link to the [file](https://github.com/woltapp/wolt_modal_sheet/blob/main/playground_navigator2/lib/bloc/router_cubit.dart). We can discuss here where you need help?

**Comment by kamami** [comment]
Hi @ulusoyca ! Thanks for the quick answer.
I am using two Cubits in my application: ChargingCubit and AuthCubit. States of both cubits need to be available and updated in the ModalSheet. Currently I am calling a function of ChargingCubit and open the sheet like this:
```
                      BlocBuilder<AuthCubit, AuthState>(
                            builder: (context, authState) {
                              return BlocBuilder<ChargingCubit, ChargingState>(
                                builder: (context, chargingState) {
                                  return InkWell(
                                    borderRadius: BorderRadius.circular(15),
                                    onTap: () {
                                        context
                                            .read<ChargingCubit>()
                                            .setSelectedConnector(
                                                widget.evse.connectors[index],
                                                widget.evse);
                                        showStartChargingModal(
                                            rootNavigatorKey.currentContext!,
                                            pageIndexNotifier,
                                            authState,
                                            chargingState);
                                      
                                    },
                                    child: Text("Open Modal")
                                  );
                                },
                              );
                            },
                          )
```
Unfortunately the updated state of ChargingCubit is not always shown correctly in the ModalSheet. 
Here is the code of showStartChargingModal():
```
                                  void showStartChargingModal(
                                      BuildContext context,
                                      ValueNotifier<int> pageIndexNotifier,
                                      List<MyContract> contracts,
                                      AuthState authState,
                                      ChargingState chargingState) {
                                    WoltModalSheet.show<void>(
                                      decorator: (child) {
                                        return BlocBuilder<AuthCubit, AuthState>(
                                          builder: (context, state) {
                                            return BlocBuilder<ChargingCubit, ChargingState>(
                                                builder: (context, state) {
                                              return child;
                                            });
                                          },
                                        );
                                      },
                                      pageIndexNotifier: pageIndexNotifier,
                                      context: context,
                                      pageListBuilder: (modalSheetContext) {
                                        return [
                                          SelectContract.build(context,
                                              pageIndexNotifier: pageIndexNotifier,
                                              contracts: contracts,
                                              authState: authState,
                                              chargingState: chargingState),
                                        ];
                                      },
                                    );
                                  }
```

**Comment by becjit** [comment]
Without looking at the code in detail here are my two cents. May be it’s
because the frame is not refreshing fast enough. Flutter refreshes at 60
fps so if state changes faster than that it might “miss” state changes. I
handled it using bloc listener. Bloc listeners are guaranteed to receive
state changes. So you can listen to state changes from one bloc in the
listener and add the event for the other bloc .

I would have suggested using bloc observer to observe state changes if you
were using blocs as I am not reasonably sure that observers doesn’t work
with cubits

**Comment by becjit** [comment]
Also I think you should use bloc provider instead if bloc builder in the
decorator

**Comment by kamami** [comment]
I also tried BlocProvider, but it did not change anything:
```
decorator: (child) {
      return BlocProvider<AuthCubit>.value(
          value: authCubit,
          child: BlocProvider<ChargingCubit>.value(
              value: chargingCubit, child: child));
    }
```
I thought about the timing of the frames as well and added a delay for opening the ModalSheet, but unfortunately it also did not fix the issue.
```
                          onTap: () {                          
                                context
                                    .read<ChargingCubit>()
                                    .setSelectedConnector(
                                        widget.evse.connectors[index],
                                        widget.evse);
                                Future.delayed(Duration(milliseconds: 1000),
                                    () {
                                  showStartChargingModal(
                                      rootNavigatorKey.currentContext!,
                                      pageIndexNotifier,
                                      authState,
                                      chargingState);
                                });
                              
                            }
```

**Comment by becjit** [comment]
I am curious , why are you passing state like this?

```
SelectContract.build(context,
                                              pageIndexNotifier: pageIndexNotifier,
                                              authState: authState,
                                              chargingState: chargingState),
```

What I would suggest is following

```
decorator: (child) {
      return BlocProvider<AuthCubit>.value(
          value: authCubit,
          child: BlocProvider<ChargingCubit>.value(
              value: chargingCubit, child: child));
    }
```

```
SelectContract.build(context,
                                              pageIndexNotifier: pageIndexNotifier,
                                            ),
```

and inside modal i.e. SelectContract.build

wrap it with BlocBuilder

That should work. 

This part is problematic as it does not pass/build the state inside modal
```

SelectContract.build(context,
                                              pageIndexNotifier: pageIndexNotifier,
                                              authState: authState,
                                              chargingState: chargingState),
```

**Comment by kamami** [comment]
How should I use BlocBuilder inside SelectContract.build?
I mean I could wrap every single widget with a separate Blocbuilder, since I need the sate in the pageTitle, topBar and the child.  But that seems to be counterintuitive. 

```
class IntentWidget {
  IntentWidget._();

  static WoltModalSheetPage build(BuildContext context,
      {required ValueNotifier<int> pageIndexNotifier,
     }) {

    return WoltModalSheetPage.withSingleChild(
                   topBar: ...,
                   pageTitle: ...,
                   child: ...
                 );
}}
```

**Comment by becjit** [comment]
I don’t recall right away how I did it. Could you try wrapping one widget
and see if that resolve the issue?

**Comment by kamami** [comment]
Yes this would work. But I thought passing the state from the parent would be better than wrapping every single widget with a BlocBuilder.

**Comment by becjit** [comment]
One more thing you can try is to wrap the child in blocbuilder inside the
decorator.
I am pretty positive that you wrapping showmodal with blocbuilder won’t
work ..
I have tried that before .. it dint work. Maybe because modal has a
different context?

So imo 1) wrapping child with blocbuilder or wrapping individual widgets
with blocbuilder will get you the desired results

**Comment by becjit** [comment]
So the decorator should have a blocprovider and inside that the child
should be wrapped with the blocbuilder

**Comment by kamami** [comment]
So you mean like this?
```
 WoltModalSheet.show<void>(
    useSafeArea: true,
    pageIndexNotifier: pageIndexNotifier,
    context: context,
    decorator: (child) => MultiBlocProvider(
      providers: [
        BlocProvider(
            create: (ctx) => AuthCubit(
                  authRepository: RepositoryProvider.of<AuthRepository>(ctx),
                )),
        BlocProvider(
            create: (ctx) => StartChargingCubit(
                  fireStoreRepository:
                      RepositoryProvider.of<FireStoreRepository>(ctx),
                  backendRepository:
                      RepositoryProvider.of<BackendRepository>(ctx),
                )),
      ],
      child: BlocBuilder<AuthCubit, AuthState>(
        builder: (context, state) {
          return BlocBuilder<ChargingCubit, ChargingState>(
              builder: (context, state) {
            return child;
          });
        },
      ),
    )
```
And how can I then access the states inside of child?

**Comment by becjit** [comment]
Your context will have the state.
Context<AuthCubit>.read().state I guess. But if you don’t want to have that
you can wrap with individual blocbuilder.
 I am not in front of computer so I can’t rest but I am positive that
having bloc provider in decorator and blocbuilder in sheet would work

**Comment by kamami** [comment]
Well I am making use of BlocBuilder for my widgets now. It works, even if I think that it is a bit overload to use so many Builders in a single page of my WoltModalSheet. Btw therefore I do not even need to use decorator. Thanks @becjit for your help!
