### ISSUE TITLE
Dispose text controllers

### ISSUE THREAD

**Issue by outrelouxhe** [woltapp/wolt_modal_sheet#47]
In the examples, the textControllers in the modal sheets are not disposed. How to proceed properly ? Thank you.

**Comment by ulusoyca** [comment]
Hi @outrelouxhe. So the text controller is part of the main content and provided as [singleChildContent](https://github.com/woltapp/wolt_modal_sheet/blob/main/lib/src/modal_page/wolt_modal_sheet_page.dart#L72). Can't you make your singleChildContent a stateful widget and dispose them in the widget's dispose method?

**Comment by chris-herring** [comment]
If we scoped the text controller to the singleChildContent then we can't access the value in the nav bar widget events. I'm disposing after I pop the sheet. Seems to work.

**Comment by ulusoyca** [comment]
@chris-herring One possible solution is moving the TextEditingController to a higher scope which can be done via the decorator field of the modal sheet. 

You can also provide a way for the singleChildContent to notify the navigation bar or the parent widget about changes without directly accessing the controller but using the `decorator` field.

An example can be found [here](https://github.com/woltapp/wolt_modal_sheet/blob/bcd903d0f394e52d1f238b8a75841f6cd259bd4b/coffee_maker/lib/home/online/store_online_content.dart#L114). 

Before updating the TextEditingController, you can check if it's mounted or if it has been disposed of. This can prevent errors related to updating a disposed object.
if (textController.hasListeners) {
    // Update the controller
}

**Comment by outrelouxhe** [comment]
Thank you @ulusoyca this is a good solution.
