### ISSUE TITLE
How could one implement onWIllPop for a form in a wolt sheet?

### ISSUE THREAD

**Issue by ozayr** [woltapp/wolt_modal_sheet#48]
I have a form as a page I want to show the normal all unsaved data will be lost before the user goes back. how could I do this?

**Comment by ozayr** [comment]
Okay I just figured you will have to manually implement it in the leadingNavBarWidget and set the pageIndexNotifier correctly

**Comment by snave00** [comment]
But how would you implement it if user dismiss the bottom sheet by dragging?

**Comment by ozayr** [comment]
If you know the  index of the form (which you most probably do) you can use the onModalDismissedWithBarrierTap and onModalDismissedWithDrag to intercept based on the notifier index value and based on the result do something -> pop or remain

**Comment by bernardoveras** [comment]
same problem...
