### ISSUE TITLE
Allow user to dictate height

### ISSUE THREAD

**Issue by baqibusiness** [woltapp/wolt_modal_sheet#50]
I hope you guys are doing well,

One thing that's missing is that we cannot control height of the sheet. Also max height seems to be specified by you when maybe a developer wants to make the sheet fullscreen. As the developer, **I want to be able to dictate the height please**.

Kind regards

**Comment by ulusoyca** [comment]
>As the developer, I want to be able to dictate the height please

You can provide the max height in percentage from 0 to 1. By default it is set to 0.9 of the screen height.

However, it is in the roadmap to provide constraints as it is in the Flutter SDK.
