### ISSUE TITLE
Allow bottom sheet title to be left aligned

### ISSUE THREAD

**Issue by robyf** [woltapp/wolt_modal_sheet#60]
Hello!

I would like to propose that there would be an additional parameter to the bottom sheet (and possibly also to the theme extension) that would allow to have the title in the navigation bar left aligned instead of centered.

The reason for this is that if an app uses titles in the app nav bar as left aligned it'd be a little incoherent to have those as centered in the bottom sheets or dialogs.

The logic for it is already implemented, see https://github.com/woltapp/wolt_modal_sheet/blob/767f4e45ed98368435731f22a6d2106eac81a54f/lib/src/widgets/wolt_navigation_toolbar.dart#L35
so it would just have to be made available to the users.

I can make a PR for it if you want :)

**Comment by robyf** [comment]
Ok so this is not as easy as I thought. `centerMiddle` on `wolt_navigation_toolbar.dart` does nothing, the top bar is rendered in the same way if that is set to `true` or `false`. `MultiChildLayoutDelegate.layoutChild` for the middle widget does so that it uses all the available space and centers the widget inside it, see for example this screenshot (where the `Text` widget is wrapped by a `ColoredBox` with red background):
<img width="440" alt="Screenshot 2023-09-29 at 17 36 00" src="https://github.com/woltapp/wolt_modal_sheet/assets/1094791/a15d7b81-4a9b-40e2-bb67-dc9ed01acf41">

So far the only way I got to have the title left align is to have it wrapped in a `Row` with `mainAxisAlignment: MainAxisAlignment.start`, this probably does not belong to the library.

I will still look into the `layoutChild` behaviour to see can that be altered in some way in the next days.

**Comment by yunusemrebakir** [comment]
Handled as part of #64
