### ISSUE TITLE
Fix the bug in the example app that remembers last page

### ISSUE THREAD

**Issue by yunusemrebakir** [woltapp/wolt_modal_sheet#62]
There is a small bug in the example app which remembers the last position. 
https://github.com/woltapp/wolt_modal_sheet/issues/57

**Comment by SunMoon97** [comment]
Hello,

I'm new to the feild of open source contribution and would appreciate some guidance on how to approach this following issue:
I haven't started working on this issue yet, and I'd like to learn how to approach it effectively. Any advice or suggestions would be greatly appreciated. Thank you for your time and assistance!

Best regards,
