### ISSUE TITLE
Instead of providing sliverList, add Sliver list in sliver type modal page.

### ISSUE THREAD

**Issue by ulusoyca** [woltapp/wolt_modal_sheet#72]
Sometimes, in some designs we need `SliverToBoxAdapter` and `SliverList` together. Currently it only takes `sliverList`

**Comment by IT-Support-AM** [comment]
Any updates on this? Is it somehow possible?

**Comment by ulusoyca** [comment]
@IT-Support-AM  The PR is in place: https://github.com/woltapp/wolt_modal_sheet/pull/95

**Comment by IT-Support-AM** [comment]
@ulusoyca Thank you!

**Comment by ulusoyca** [comment]
PR is merged. Closing the issue.

**Comment by ulusoyca** [comment]
@IT-Support-AM This is released now: https://github.com/woltapp/wolt_modal_sheet#migration-from-01x-to-020
