### ISSUE TITLE
App cannot build on older Flutter verrsion - Throws `Error: Member not found: 'MediaQuery.sizeOf`

### ISSUE THREAD

**Issue by mdhanis31** [woltapp/wolt_modal_sheet#76]
Could not build the application for the simulator.
Error (Xcode): ../../.pub-cache/hosted/pub.dev/wolt_modal_sheet-0.1.3/lib/src/content/components/paginating_group/main_content_animated_builder.dart:51:36: Error: Member not found: 'MediaQuery.sizeOf'.

**Comment by ulusoyca** [comment]
Hi @mdhanis31 this API is added recently to Flutter. If you are not using latest versions of Flutter you wont be able to get this.

@TahaTesser This is something we should revert because this API is prevents using the package with the older versions of Flutter. Ping @yunusemrebakir maybe a hotfix?

**Comment by ulusoyca** [comment]
@mdhanis31 We just released 0.1.4 that should fix your issue if your Flutter version is at least has the version released in last 1 year
