### ISSUE TITLE
Add linter to the repo

### ISSUE THREAD

**Issue by yunusemrebakir** [woltapp/wolt_modal_sheet#77]
![Screenshot 2023-10-20 at 08 09 56](https://github.com/woltapp/wolt_modal_sheet/assets/7239330/d121c207-a2c2-4c6b-aea9-51209ec98bd4)

**Comment by ulusoyca** [comment]
@TahaTesser is adding a linter check before merge soon 🚀

**Comment by ulusoyca** [comment]
@yunusemrebakir We can close this since @TahaTesser added merge checks and fixed the issues. Let's have a dry run before uploading the next hotfix version.
