### ISSUE TITLE
Add Pull Request checks

### ISSUE THREAD

**Issue by TahaTesser** [woltapp/wolt_modal_sheet#83]
To maintain the codebase and ensure PR changes are analyzed before merging we need to take the following steps:

Once this is merged https://github.com/woltapp/wolt_modal_sheet/pull/82. 

### Add `Ruleset` for the default branch  (@ulusoyca this requires you)
1. Open the wolt_modal_sheet GitHub repostory on the GitHub website.
2.  Click on the `settings` tab
![image](https://github.com/woltapp/wolt_modal_sheet/assets/48603081/119ed370-54a4-44fa-b8d0-e3954c56e23d)
3. On the left side menu, click `Rules` section to expand and choose `Rulesets`
![image](https://github.com/woltapp/wolt_modal_sheet/assets/48603081/34e594ce-285f-4508-be3f-4e27651712fd)
4. Click the `New ruleset` and select `New branch ruleset`
![image](https://github.com/woltapp/wolt_modal_sheet/assets/48603081/b8eca4c1-166a-4071-ae11-0e036995d00d)
5. Give it a name, `default-branch` (or anything you like) and set the `Enforcement status` to `active`.
![image](https://github.com/woltapp/wolt_modal_sheet/assets/48603081/c05d2098-f6fe-4443-8df3-3b3517dbd4b8)
6. Match the following settings
![image](https://github.com/woltapp/wolt_modal_sheet/assets/48603081/bc77d2ff-a0b8-41d5-a73f-b1a0448f5532)
![image](https://github.com/woltapp/wolt_modal_sheet/assets/48603081/97c2d22c-8e3f-4ec4-afc4-380d65caf289)

**Comment by TahaTesser** [comment]
After merging https://github.com/woltapp/wolt_modal_sheet/pull/82  you should the `flutter analyze` checks in the "Enter the name of a status check" box.

**Comment by ulusoyca** [comment]
@TahaTesser I guess it works!
<img width="946" alt="image" src="https://github.com/woltapp/wolt_modal_sheet/assets/13782003/9e3d18d5-9e37-4c38-8bde-3d8cf1131569">

**Comment by TahaTesser** [comment]
@ulusoyca 
Perfect. Let me fix the analyze issues and to make it green

**Comment by TahaTesser** [comment]
Added Melos in the check to boostrap the whole project incuding subfolders and make analyzer pass.

**Comment by TahaTesser** [comment]
> @TahaTesser I guess it works! <img alt="image" width="946" src="https://user-images.githubusercontent.com/13782003/277109237-9e3d18d5-9e37-4c38-8bde-3d8cf1131569.png">

All green!
![image](https://github.com/woltapp/wolt_modal_sheet/assets/48603081/91aa2575-4d2d-4db2-a20e-389b5339f09c)
