### ISSUE TITLE
Drag ModalSheet when inner ListView reaches end

### ISSUE THREAD

**Issue by kamami** [woltapp/wolt_modal_sheet#86]
Is it possible to drag the sheet down without lifting the finger, when my scrollable widget reaches the top again?
Just like [DraggableScrollableSheet](https://api.flutter.dev/flutter/widgets/DraggableScrollableSheet-class.html)?

**Comment by ulusoyca** [comment]
Hi, unfortunately this package does not work the same way as `DraggableScrollableSheet`
