### ISSUE TITLE
Replace asset images with network images in the minimal `example`

### ISSUE THREAD

**Issue by TahaTesser** [woltapp/wolt_modal_sheet#91]
The current minimal uses asset images when run won't load images unless the repository is cloned.

![Screenshot 2023-10-31 at 11 10 26](https://github.com/woltapp/wolt_modal_sheet/assets/48603081/51edb006-87b5-40fa-837e-c509add10752)

### Steps to reproduce
1. Copy the sample from the pub page
![Screenshot 2023-10-31 at 11 12 23](https://github.com/woltapp/wolt_modal_sheet/assets/48603081/f3abb2ca-e41e-4639-94b8-add1926460db)

2. Run the minimal example in your own app or IDX

**Comment by Drugjudy** [comment]
@ulusoyca please review my code edit, thanks

**Comment by ulusoyca** [comment]
@Drugjudy Thanks for your contribution. Can you please check the contribution guideline and create a PR?

**Comment by Drugjudy** [comment]
> @Drugjudy Thanks for your contribution. Can you please check the contribution guideline and create a PR?

All done, thanks
