### ISSUE TITLE
initial size

### ISSUE THREAD

**Issue by manuduxi** [woltapp/wolt_modal_sheet#92]
Hello Guys,

does anyone have a solution to set a initial size? We're using wolt modal sheet on a Map and even if the max child size is 1, it should not automatically open with max height, we would like to be able to define the initial size.

Flutter's bottom modal sheet for example has initialChildSize value

Thank you in advance

**Comment by ulusoyca** [comment]
@manuduxi The height of the package can be set with `[maxPageHeight](https://github.com/woltapp/wolt_modal_sheet/blob/1621c402029d513a499d06d2bcdbcfdeeb774ab6/lib/src/wolt_modal_sheet.dart#L85)` field whose value can be between 0 and 1. 1 means full screen. If you want to give precise height, you would need to first calculate the device height, and then map it to your initial heigh in 0..1 range 

```dart
maxPageHeight: initial_height/device_height,
```

I hope this helps!

**Comment by manuduxi** [comment]
> @manuduxi The height of the package can be set with [maxPageHeight](https://github.com/woltapp/wolt_modal_sheet/blob/1621c402029d513a499d06d2bcdbcfdeeb774ab6/lib/src/wolt_modal_sheet.dart#L85) field whose value can be between 0 and 1. 1 means full screen. If you want to give precise height, you would need to first calculate the device height, and then map it to your initial heigh in 0..1 range
> 
> ```dart
> maxPageHeight: initial_height/device_height,
> ```
> 
> I hope this helps!

thank your for clarifying how the initial height can be set precisely, however I would like to have the maxPageHeight set to 1, so full screen height, but not by default when the BottomSheet opens. It should open at minPageHeight 0.3 and then be draggable to maxPageHeight 1

**Comment by ulusoyca** [comment]
I see your point. It is the same issue opened at https://github.com/woltapp/wolt_modal_sheet/issues/86. Unfortunately this package does not support [DraggableScrollableSheet](https://api.flutter.dev/flutter/widgets/DraggableScrollableSheet-class.html) behavior yet, and not planned in short term.

**Comment by manuduxi** [comment]
Alright, I will try to figure out a workaround then.
Thank you for your help
