### ISSUE TITLE
Nav bar height parameter is not being respected when min page height is on the higher side

### ISSUE THREAD

**Issue by becjit** [woltapp/wolt_modal_sheet#93]
I want o to have a full screen bottom sheet.
For that I am setting the following parameters

```
 minPageHeight: .9,
      maxPageHeight: 1,

```
In .withsinglechild then I am setting nav bar height as 
```

  navBarHeight: 36,
      hasTopBarLayer: true,
      isTopBarLayerAlwaysVisible: true,
```

The result is following
<img width="363" alt="Screenshot 2023-11-05 at 12 31 38 PM" src="https://github.com/woltapp/wolt_modal_sheet/assets/2213422/df2f69a4-d68f-4d21-a9e8-766a92de2f43">

what I expect is following

<img width="373" alt="Screenshot 2023-11-05 at 12 35 27 PM" src="https://github.com/woltapp/wolt_modal_sheet/assets/2213422/23064099-8fcd-484b-9a25-2b833360e0fe">

Please let me know what am I missing?

**Comment by ulusoyca** [comment]
Hi @becjit can you try to add `forceMaxHeight` parameter to true and let us know if this helps?

**Comment by becjit** [comment]
Yes it does. Thanks
Abhijit

**Comment by ulusoyca** [comment]
I am happy to hear that this helps. However, this is still a bug that we need to handle. Thanks for reporting.
