### ISSUE TITLE
Replace deprecated usages in `wolt_modal_sheet_test`

### ISSUE THREAD

**Issue by yunusemrebakir** [woltapp/wolt_modal_sheet#99]
We should replace the deprecated usages in the `test/wolt_modal_sheet_test.dart`

![image](https://github.com/woltapp/wolt_modal_sheet/assets/7239330/58ace419-6968-4e11-b59a-05890e72e428)

**Comment by TahaTesser** [comment]
These APIs are **deprecated after 3.7.2.** 
They're in the codebase to maintain backward compatibility,  for at least Flutter version 3.7.2.
This APIs should be replaced when the minimum Flutter version required for the package is updated.

**Comment by yunusemrebakir** [comment]
Good point @TahaTesser, my local version is higher and I missed that! 😅
